### PR TITLE
px4escv1.6

### PR DESCRIPTION
**Pull request by davids5**
@bendyer, FYI @LorenzMeier @pkocmoud

Redone - due to git weirdness 

This PR will name the files per mavlink/mavlink#414 (comment)
It also resolved the boot-loop, I would suspect you can back out the "union" changes.

It Drives uavcan identification from make file
Use correct stm32F446 memory map definitions in linker file
Use px4 bootloader compatible memory map for px4esc1.6 Params at bottom of memory (on F4 memory)

This was tested with the PX4/Firmware nuttx_next_cmake bootloaders and the one's in this tree on both px4esc1.6 and s2740vc (please double check the s2740vc as I do not have an end to end test)

### CODE REVIEW

**Comment by bendyer** [comment]
All looks OK, but this doesn't actually fix #3228, and in fact disables the fix I put in place for it — the problem is that the firmware filename for both boards ends in `<githash>.bin`, so when the files are copied to the cache directory, the filenames are the same and the wrong firmware can be loaded.

The fix for #3228 has to be done in libuavcan itself.

**Comment by davids5** [comment]
Sorry I am not understanding how the file gets renamed. SD cards are created by removing the the leading ddd.nnnnnnnnnn and the trailing version

org.pixhawk.px4cannode-v1-1.0-0.1.9bd57372.bin -> px4cannode-v1.9bd57372.bin

**Comment by LorenzMeier** [comment]
@bendyer The concept is that the file name is ```<boardname><githash>.bin``` which should not create any conflicts.

@davids5 I just realised that this copy command here is wrong and needs to be fixed to copy only the board name + git hash:
https://github.com/PX4/Firmware/blob/master/.travis.yml#L108-L109

**Comment by bendyer** [comment]
Thanks @davids5!

**Pull request merged**
